name: '${project.name}'
version: '${project.version}'
main: pl.ynfuien.scavengerHunt.ScavengerHunt
api-version: '1.21'
authors: [ Ynfuien ]
softdepend: [ PlaceholderAPI, Vault, Essentials ]
description: '${project.description}'

commands:
  scavengerhunt:
    aliases: [hunt]
    description: Main plugin command
    permission: scavengerhunt.command